name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Show Build SDK
      run: xcodebuild -showsdks
    
    - name: Show Available Destinations
      env:
        scheme: ${{ matrix.run-config['scheme'] }}    
      run: xcodebuild -scheme ${scheme} -showdestinations
